name: example
description: A new Flutter project.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_ibm_watson:
    path: ../
  image_picker: ^0.6.7+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  audioplayers: ^0.15.1
  path_provider: ^1.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

