name: flutter_ibm_watson
description: The flutter_ibm_watson makes it easy to integrate IBM Watson
version: 0.0.2
author: Victor Alfonso Rodas Oña <victordevcode@gmail.com>
homepage: https://github.com/VictorRancesCode/flutter_ibm_watson

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

environment:
  sdk: '>=2.0.0 <3.0.0'